apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xp5g9llcr-dotnet-basic
  janus-idp.io/tekton: xp5g9llcr-dotnet-basic
  backstage.io/kubernetes-id: xp5g9llcr-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xp5g9llcr-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
